### ISSUE TITLE
issue with menu header

### ISSUE THREAD

**Issue by AustinHatem** [cssninjaStudio/bulkit#1]
the menu will have a scroll bar when the page is at a certain size on windows in chrome.

**Comment by cssninjaStudio** [comment]
Can you please provide a Screenshot of the problem ?

**Comment by cssninjaStudio** [comment]
Bulkit has been upgraded to Bulma 0.7 and the navbar component has been completely rewritten. Therefore, this issue is no more relevant. Feel free to reopen if needed.

**Comment by cssninjaStudio** [comment]
Added missing font files.
