### ISSUE TITLE
having trouble finding the documentation

### ISSUE THREAD

**Issue by AustinHatem** [cssninjaStudio/bulkit#2]

**Comment by AustinHatem** [comment]
the documentation does not open.

**Comment by arianpasquali** [comment]
same here

**Comment by cssninjaStudio** [comment]
Hello, sorry for the late answer. The documentation won't open properly if not dropped in the public folder of a local web server, like WAMP, MAMP or XAMPP if you are on windows.  You also have other options : 

* Open a terminal and change directory to the root of the documentation folder and run the following command : 

`docsify serve`

This should launch a development server and a browser window with the documentation. You can also find it at http://localhost:3000
