### ISSUE TITLE
Button text vertical alignment

### ISSUE THREAD

**Issue by tonycodes** [cssninjaStudio/bulkit#5]
Hi,

The 'Get Started Now' not vertically aligned correctly (seems a bit high?) on Chrome Version 66.0.3359.117 (Official Build) (64-bit)

![screen shot 2018-05-02 at 13 02 07](https://user-images.githubusercontent.com/7568679/39522084-1d417b94-4e09-11e8-94ff-e4f6f30b0272.png)

Would you be able to take a look at this please?

**Comment by cssninjaStudio** [comment]
Hey Tony,

Well this is probably due to the font this button is using : **Nexa font**. It sometimes has a strnage behaviour with line heights. Replace the font family from the button and this will solve it.

**Comment by cssninjaStudio** [comment]
I guess that is all for this one.
