### ISSUE TITLE
Cannot run npm install 

### ISSUE THREAD

**Issue by possibly1** [cssninjaStudio/bulkit#7]
trying to grab all the new css files, and install the updated version 2 however the install fails 

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-64_binding.node":

**Comment by cssninjaStudio** [comment]
What is your node js version ?

**Comment by possibly1** [comment]
Originally it was 10, downgraded to 8.x.x . Overall the route issue was node-sass compatibility with windows. After getting python 2.x.x and such running I was able to fix the problem. Incase anyone runs into similar issues you'll need Node-sass, python 2.x.x, node-gyp, and I opted for Visual c++ build tools though i'm sure there are other workarounds. https://github.com/nodejs/node-gyp#on-windows
