### ISSUE TITLE
Bulkit KitDemo gulp issues mac Mojave

### ISSUE THREAD

**Issue by supersmart-at** [cssninjaStudio/bulkit#9]

**Comment by cssninjaStudio** [comment]
The problem is your node version. You should use a v6 node distribution. Everything should work as expected. We’ll redirect you to a thread that talks about on the forum when we activate your account.

**Comment by stormdi** [comment]
This should work

rm -rf node_modules
rm -rf package-lock.json
npm install

**Comment by supersmart-at** [comment]
I had an issue with brew, but found a workaround. I was redirected to the forum and posted my solution there:


now running with node: v6.14.4:

1. [howto node@6](https://medium.com/@katopz/how-to-install-specific-nodejs-version-c6e1cec8aa11) with brew on medium
2. ...
   `brew unlink node && brew link --force node@6`
3. ...

```
cd kit-demo
node -v
npm -v
npm install npm@latest -g
npm install gulp -g
npm install
gulp init
gulp build
gulp default
```
